http:
    address: "0.0.0.0:8080"
    uploads:
        forbid: [".php", ".exe", ".bat"]
    workers:
        command: "php bin/console baldinof:roadrunner:worker"
        relay: "unix://var/roadrunner.sock"
static:
    dir:   "public"
    forbid: [".php", ".htaccess"]

metrics:
    address: 0.0.0.0:2112
    collect:
        app_metric:
            type:    histogram
            help:    "Custom application metric"
            labels:  ["type"]
            buckets: [0.1, 0.2, 0.3, 1.0]
health:
    address: 0.0.0.0:2113