version: '3.7'

volumes:
    db_data: {}
    db_test_data: {}

services:
    php:
        image: cyradin/php-roadrunner:7.4-latest
        environment:
            WAIT_FOR_HOST: postgres
            WAIT_FOR_PORT: 5432
            WAIT_FOR_TIMEOUT: 30
            DEV_MODE: 0
        restart: always
        volumes:
            - .:/srv:rw
        networks:
            local:
            f1monkey:
                aliases:
                    - f1monkey-CHANGE_ME
    postgres:
        image: postgres:12.3-alpine
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - "db_data:/var/lib/postgresql/data"
        networks:
            local:

    postgres_test:
        image: postgres:12.3-alpine
        environment:
            POSTGRES_DB: db_test
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - "db_test_data:/var/lib/postgresql/data"
        networks:
            local:

networks:
    f1monkey:
        external: true
    local: