# Expose your documentation as JSON swagger compliant
app.swagger_all:
    path: /doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger, area: default }

app.swagger_versions:
    path: /{area}/doc.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger, area: default }

app.swagger_ui:
    path: /{area}/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: default }
