monolog:
    handlers:
        main:
            type: filter
            handler: file_and_logstash
            channels: ["!event", "!doctrine", "!console", "!security", "!request"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console", "!security", "!request"]
            level: debug
            handler: file_and_logstash

        file_and_logstash:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            channels: ["!event", "!doctrine", "!console", "!security", "!request"]
            level: debug
            handler: logstash
        logstash:
            type: service
            id: monolog.handler.logstash_handler
            channels: ["!event", "!doctrine", "!console", "!security", "!request"]
            level: debug