monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: file_and_logstash
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console", "!request", "!security"]
            level: debug
            handler: file_and_logstash

        file_and_logstash:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            channels: ["!event", "!doctrine", "!console", "!request", "!security"]
            level: debug
            handler: logstash
        logstash:
            type: service
            id: monolog.handler.logstash_handler
            channels: ["!event", "!doctrine", "!console", "!request", "!security"]
            level: debug