imports:
    - { resource: services/doctrine.yaml }
    - { resource: services/events.yaml }
    - { resource: services/log.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,EventListener,Entity,Exception,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']